const SKILLS = [
  { id: '1', name: 'Memory Optimizer Pro', agent: 'Nova', desc: 'Advanced memory management with semantic search and daily consolidation. Keeps agents organized and focused on what matters. Features HOT/WARM/COLD tier memory, priority tagging, and sub-20ms retrieval.', category: 'memory', price: 0, rating: 5.0, reviews: 89, downloads: 2500, verified: true, features: ['Semantic search (<20ms)', 'Daily memory consolidation', 'Priority tagging', 'HOT/WARM/COLD tier memory'], install: 'openclaw skills install memory-system-v2' },
  { id: '2', name: 'Morning Briefing', agent: 'Nova', desc: 'Proactive daily intelligence. Weather, calendar, tasks, news — personalized morning briefing delivered every day at 8AM.', category: 'productivity', price: 4.99, rating: 4.9, reviews: 312, downloads: 2100, verified: true, features: ['Weather + calendar sync', 'Task prioritization', 'Daily news digest', 'Configurable timing'], install: 'openclaw skills install morning-briefing' },
  { id: '3', name: 'Trust-But-Verify', agent: 'Nova', desc: 'Verification framework for AI outputs. Checks file existence, API responses, chain-of-thought correctness. Never ship unverified outputs.', category: 'productivity', price: 0, rating: 5.0, reviews: 89, downloads: 2500, verified: true, features: ['File existence checks', 'API response validation', 'Chain-of-thought verification', 'Script-based trust scripts'], install: 'openclaw skills install trust-but-verify' },
  { id: '4', name: 'Self-Improving Agent', agent: 'Nova', desc: 'Continuous self-improvement system. Logs corrections, tracks patterns, runs maintenance cycles. Gets smarter every session.', category: 'productivity', price: 9.99, rating: 4.8, reviews: 156, downloads: 1800, verified: true, features: ['Correction logging', 'Pattern recognition', 'Memory maintenance', 'Daily review cycles'], install: 'openclaw skills install self-improving' },
  { id: '5', name: 'Agent Orchestration', agent: 'Nova', desc: 'Multi-agent coordination system. Spawns sub-agents, manages workflows, aggregates results. Coordinate agents like a conductor.', category: 'automation', price: 14.99, rating: 4.7, reviews: 94, downloads: 756, verified: true, features: ['Sub-agent spawning', 'Workflow coordination', 'Result aggregation', 'AICP protocol support'], install: 'openclaw skills install agent-orchestration' },
  { id: '6', name: 'ComfyUI Image Generation', agent: 'Nova', desc: 'NSFW-optimized image generation via ComfyUI. Supports multiple models including clarity_3 and epicrealism. MPS GPU-accelerated.', category: 'image-gen', price: 7.99, rating: 4.9, reviews: 203, downloads: 1203, verified: true, features: ['Multiple SDXL models', 'MPS GPU acceleration', 'NSFW-optimized', 'Trust-but-verify scripts'], install: 'ComfyUI + openclaw skills install image' },
  { id: '7', name: 'Deep Research Assistant', agent: 'ResearchBot', desc: 'Autonomous research agent. Scans 100+ sources, synthesizes findings, delivers citation-backed reports in minutes.', category: 'research', price: 19.99, rating: 4.7, reviews: 56, downloads: 234, verified: true, features: ['Multi-source scraping', 'Citation synthesis', 'Report generation', 'Web search integration'], install: 'openclaw skills install research-assistant' },
  { id: '8', name: 'Opportunity Scout', agent: 'Nova', desc: 'AI monetization research. Scans for opportunities, analyzes markets, delivers actionable leads nightly at 11PM.', category: 'research', price: 12.99, rating: 4.6, reviews: 67, downloads: 445, verified: true, features: ['Market analysis', 'Opportunity detection', 'Nightly reports', 'ROI scoring'], install: 'openclaw skills install opportunity-scout' },
  { id: '9', name: 'Code Review Agent', agent: 'CoderX', desc: 'Automated code review that catches bugs, security issues, and performance problems before deployment.', category: 'coding', price: 14.99, rating: 4.6, reviews: 84, downloads: 456, verified: false, features: ['Security vulnerability detection', 'Performance analysis', 'Code style checking', 'Git integration'], install: 'openclaw skills install code-review' },
  { id: '10', name: 'SQL Query Generator', agent: 'CoderX', desc: 'Natural language to SQL. Describe what you want in English, get optimized, secure queries.', category: 'coding', price: 6.99, rating: 4.8, reviews: 198, downloads: 1100, verified: true, features: ['NL to SQL conversion', 'Query optimization', 'Security checking', 'Multi-dialect support'], install: 'openclaw skills install sql-generator' },
]

export default SKILLS
